---

- name: Check kubernetes already installed
  stat: 
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_state 

- name: Initialaize master node
  command: >
    kubeadm init
    {{ kubeadm_init_opts }}
  register: kubeadm_init
  failed_when: false
  when: not kubernetes_init_state.stat.exists

- name: Print  init output
  debug:
      var: kubeadm_init.stdout
      verbosity: 2
  when: not kubernetes_init_state.stat.exists

- name: check ./kube directory  
  file:
    path: ~/.kube
    state: directory

- name: symlink admin config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link 

- name: register kubever
  shell: export kubever=$(kubectl version | base64 | tr -d '\n'); 
         kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever" 
         
- name: set join command
  command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result

- name: set join command globally
  set_fact:
    kuberntes_join_command: "{{ kubernetes_join_command_result.stdout }}" 
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
  