---

- name: Check kubernetes already installed
  stat: 
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_state 

- name: Initialaize master node
  command: >
    kubeadm init
  register: kubeadm_init
  failed_when: false
  when: not kubernetes_init_state.stat.exists

- name: Print init output
  debug:
      var: kubeadm_init.stdout
      verbosity: 0
  when: not kubernetes_init_state.stat.exists

- name: check ./kube directory  
  file:
    path: ~/.kube
    state: directory

- name: symlink admin config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link 

- name: register kubever
  shell: export kubever=$(kubectl version | base64 | tr -d '\n'); 
         kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever" 
         